name: hidenseek
channels:
  - conda-forge
dependencies:
  - python==3.8
  - numpy
  - scipy
  - pandas
  - xarray==0.15.1
  - seaborn
  - matplotlib
  - ipykernel
  - nodejs
  - ipywidgets
  - scikit-learn
  - statsmodels
  - tqdm
  - python-dotenv
  - numba
  - cython
  - cached-property
  - munkres
  - pip
  - pony
  - moviepy
  - ipympl
  - kneed
  - plotly
  - pkg-config
  - scikit-image
  - jupyterlab
  - jupytext
  - pip:
    - autograd==1.3
    - elephant==0.10.0
    - future==0.18.2
    - ipynb==0.5.1
    - kaleido==0.2.1
    - neo==0.9.0
    - opencv-python==4.5.5.62
    - pynndescent==0.5.2
    - quantities==0.12.4
    - umap-learn==0.5.1
    #- git+https://github.com/lindermanlab/ssm.git
